Add UserNotifications Framework for iOS 10+
delba/Permission pull request #90
Opened 2017-01-20 08:53 UTC by mrgrauel

I added a permission for the new notification framework UserNotifications in iOS 10 to request permission with the new api.

* add permission `UserNotification`
* add configuration `PERMISSION_USERNOTIFICATIONS`
* add permissionType `userNotifications`
* removed the file private static variable `_notification` cause it's never read
* did **not** change the `requestedNotifications` default cause it returns the same information

---

I tried to keep it in the structure you designed the framework.

2017-01-20 09:10 UTC, mrgrauel commented
On my local machine the tests do run. Does anybody has an idea why the checks fail?

2017-01-31 06:28 UTC, mrgrauel commented
@delba what's going on?

2017-02-05 01:43 UTC, pasevin commented
Any chance this is going to be merged?

2017-03-05 21:09 UTC, delba requested changes

2017-03-05 21:09 UTC, delba commented on Source/Permission.swift
> -    fileprivate static var _notifications: Permission?
This variable is used to retain the permission as stated in the comment above.

2017-03-05 21:09 UTC, delba commented on Source/Permission.swift
> -        _notifications = permission
`_notifications` is used to retain the permission

2017-03-05 21:09 UTC, delba commented on Source/Permission.swift
> -        _notifications = permission
Same comment as above

2017-03-05 21:09 UTC, delba commented on Source/Permission.swift
> -        _notifications = permission
Again

2017-03-05 21:09 UTC, delba commented on Source/Permission.swift
> +        return Permission(type: .userNotifications(options))
We need to retain the permission with a private var like in the case of `notifications` (e.g: `_userNotifications`)

2017-03-05 21:09 UTC, delba commented on Source/PermissionType.swift
> +#if PERMISSION_NOTIFICATIONS
Should be `PERMISSION_USERNOTIFICATIONS`

2017-03-05 21:09 UTC, delba commented on Permission.podspec
> +  s.version      = "2.1.0"
I prefer to change it just before pushing it (and it's dependent on the git tag)

2017-03-05 21:09 UTC, delba commented on Permission.podspec
> +    no.pod_target_xcconfig = { "SWIFT_ACTIVE_COMPILATION_CONDITIONS"  => "PERMISSION_USERNOTIFICATIONS" }
Could we rename `PERMISSION_USERNOTIFICATIONS` to `PERMISSION_USER_NOTIFICATIONS` for the sake of consistency please?

2017-03-05 21:09 UTC, delba commented on Source/PermissionTypes/UserNotifications.swift
> +    var statusUserNotifications: PermissionStatus {
Could we keep the structure of the `Motion` permission (that also uses "synchronous" calls) please ?

2017-03-05 21:10 UTC, delba commented
Hi @mrgrauel, thanks a lot for the PR! There are a just few changes to do before merging though.
Thanks!

2017-03-06 08:31 UTC, mrgrauel commented
Good Morning @delba, is it now as you want it?

2017-03-08 11:27 UTC, mrgrauel commented on Source/Permission.swift
> -        _notifications = permission
Changed

2017-03-08 11:27 UTC, mrgrauel commented on Source/Permission.swift
> -        _notifications = permission
Changed

2017-03-08 11:27 UTC, mrgrauel commented on Source/Permission.swift
> -        _notifications = permission
Changed

2017-03-08 11:28 UTC, mrgrauel reviewed
Changed

2017-03-08 11:28 UTC, mrgrauel commented on Source/Permission.swift
> -        _notifications = permission
changed

2017-04-05 07:14 UTC, mrgrauel commented
@delba I changed everything. I dunno why it still says that a change request is open.

2017-05-03 08:00 UTC, mrgrauel commented
@delba Hello?!?!?!

2017-06-10 23:56 UTC, otymartin commented
@delba Has this issue been fixed? I still get these xcode 10 deprecation warnings

2017-06-16 19:08 UTC, rob5408 approved these changes

2017-06-16 19:14 UTC, rob5408 commented
^^ @delba Sorry about that, I thought I was on my fork. I know it doesn't actually merge the PR, but why does GitHub even give me the option. :\

2017-06-22 12:43 UTC, JeromeTan1997 commented
@delba Please merge this PR

2017-07-27 23:56 UTC, pasevin commented
Loosing hope :/

2017-09-14 10:24 UTC, Dschee commented
Hey everybody, I've given up on waiting for @delba to answer and merge our PRs. Instead I've integrated my PR #94 and this PR into my fork, created its own CocoaPods entry so we can continue using this framework and merging our improvements together. Feel free to star and send your PRs to my fork in the future. I will try to review them from time to time:

https://github.com/Dschee/Permission

2017-09-15 05:32 UTC, otymartin commented
@Dschee nice move 👍

2019-11-12 14:40 UTC, delba commented
Hi @mrgrauel, the project has been updated to the latest Swift version and now uses `UserNotifications` (https://github.com/delba/Permission/blob/master/Source/Types/Notifications.swift).

2019-11-12 14:40 UTC, closed without merging